name: Android CI

on:
  push:
    branches: [ "main", "dev", "safestride-app" ]
  pull_request:
    branches: [ "main", "dev", "safestride-app" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      working-directory: safestride-app

    - name: Run unit tests
      run: ./gradlew :app:testDebugUnitTest
      working-directory: safestride-app

    - name: Build with Gradle
      run: ./gradlew assembleDebug
      working-directory: safestride-app
